name: FastAPI CI

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repo
    - name: 25ds2000003@ds.study.iitm.ac.in
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
        pip install numpy

    # 4. Run tests (or simple sanity check)
    - name: Run sanity check
      run: |
        python -c "from api.index import app; print('FastAPI app imported successfully')"
